teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: true
    enable_button: 10         # R1 (check mapping)
    enable_turbo_button: -1   # Unused

    axis_linear:
      x: 1                    # Left stick up/down
      y: 0                    # Left stick left/right

    axis_angular:
      yaw: 2                  # Right stick left/right

    scale_linear:
      x: 0.15
      y: 0.15
    scale_angular:
      yaw: 0.8

joy_node:
  ros__parameters:
    deadzone: 0.2
