Sample config file (motors.yaml):
joints:
  - name: motor_one
    id: 1
    mode: velocity
  - name: motor_two
    id: 2
    mode: velocity
  - name: motor_three
    id: 3
    mode: velocity
  - name: motor_four
    id: 4
    mode: velocity
  - name: motor_five
    id: 5
    mode: velocity
  - name: motor_six
    id: 6
    mode: velocity
  - name: motor_seven
    id: 7
    mode: velocity
  - name: motor_eight
    id: 8
    mode: velocity