planning_plugins:
  - ompl_interface/OMPLPlanner
planning_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
  - default_planning_request_adapters/FixStartStateBounds
  - default_planning_request_adapters/FixStartStateCollision
  - default_planning_request_adapters/FixWorkspaceBounds
response_adapters:
  - default_planning_response_adapters/DisplayMotionPath

arm:
  planner_configs:
    - RRTConnect
    - RRTstar
    - TRRT
    - PRM
    - PRMstar
  projection_evaluator: joints(joint1,joint2)
  longest_valid_segment_fraction: 0.005

gripper:
  planner_configs:
    - RRTConnect
    - RRTstar
    - TRRT
    - PRM
    - PRMstar
  projection_evaluator: joints(joint7)
  longest_valid_segment_fraction: 0.005

planner_configs:
  RRTConnect:
    type: geometric::RRTConnect
    range: 0.0  # Max motion length
    optimization_objective: PathLength
  RRTstar:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05
    delay_collision_checking: 1
  TRRT:
    type: geometric::TRRT
    range: 0.0
    goal_bias: 0.05
    max_states: 100
    temperature: 10e-6
    frontier_threshold: 0.0
    frontier_node_ratio: 0.1
    k_constant: 20.0
  PRM:
    type: geometric::PRM
    max_nearest_neighbors: 10
  PRMstar:
    type: geometric::PRMstar
